### ISSUE TITLE
Incomplete language translation

### ISSUE THREAD

**Issue by dcrlove2021** [decred/dcrdex#1917] opened 2022-10-23 03:44 UTC
The language translation is incomplete. I will put the screenshot after experience here，This is Chinese！

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/82247290/197372186-733d52a7-ba9d-40d3-b185-a94add9d8ea5.png">

<img width="774" alt="image" src="https://user-images.githubusercontent.com/82247290/197372213-009d71ba-bd70-464a-b56f-b1742e362380.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/82247290/197372231-54957709-7e24-49d8-bd81-77d9981e45be.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/82247290/197372253-a7ee4491-bdec-4455-b8a9-33ddc038c47e.png">

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/82247290/197372273-1e34145b-0521-4940-80fc-e65d052c2d24.png">

<img width="550" alt="image" src="https://user-images.githubusercontent.com/82247290/197372289-297a3ba1-1554-4153-b3a5-bfc9501ce999.png">

<img width="971" alt="image" src="https://user-images.githubusercontent.com/82247290/197372304-50da3c53-300f-4192-910b-82a33d324c65.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/82247290/197372412-0796d078-cddd-4eed-9490-b261f8aee41c.png">

**Comment by dcrlove2021** [comment] 2022-10-23 03:46
I hope I didn't disturb development process

**Comment by chappjc** [comment] 2022-10-23 04:11
Duplicate of https://github.com/decred/dcrdex/issues/1454
Other missing transitions are know as well

**Closed by chappjc** 2022-10-23 04:11 UTC

**Comment by chappjc** [comment] 2022-10-23 04:13
Unreleased updates: https://github.com/decred/dcrdex/pull/1871

**Comment by dcrlove2021** [comment] 2022-10-24 11:27
ok
