### ISSUE TITLE
ui: 0-qty market order(s) lurking in order book

### ISSUE THREAD

**Issue by norwnd** [decred/dcrdex#2259] opened 2023-03-27 06:56 UTC
Saw 0-qty market order show up in order book (on master mainnet, view-only mode = without creating account). It disappears and reappears (the amount of orders it consists of changes from time to time, could be just 1 or could be 5 for example, qty stays at 0 though) after page refresh or navigating from/to `/markets` page:

[0-qty-market-order-in-the-book.webm](https://user-images.githubusercontent.com/112318969/227863356-a971e8dd-f3fb-4af3-baeb-d6963ee128d0.webm)

<br>

I tried to shake it off restarting **dexc** 2-3 times, it didn't help (ghost orders are still there) which suggests the server is either fully responsible or heavily contributing (e.g. order book gets corrupted when client fetches it from server) to this issue.

Full log: [0-qty-market-order.txt](https://github.com/decred/dcrdex/files/11075553/0-qty-market-order.txt). No errors in console, running just 1 **dexc** instance (no funny stuff with 2 instances interfering with each other).

Might have same root cause as https://github.com/decred/dcrdex/pull/1543, could potentially be resolved (or addressed at least partially) by: https://github.com/norwnd/dcrdex/pull/1 + https://github.com/norwnd/dcrdex/pull/2 + https://github.com/norwnd/dcrdex/pull/4

**Comment by chappjc** [comment] 2023-03-27 12:44
Duplicate of https://github.com/decred/dcrdex/issues/1929 which is also a dip of #1139

**Comment by chappjc** [comment] 2023-03-27 12:44
Duplicate of https://github.com/decred/dcrdex/issues/1929 which is also a dup of #1139

**Comment by buck54321** [comment] 2023-03-27 12:45
It's not **actually** a zero-quantity market order. We combine the value of all market orders into that row, which should be hidden if the value is zero, but obviously have a bug.

**Comment by chappjc** [comment] 2023-03-27 12:57
This one is due to a cancel order, unlike the depth chart issues you solved in https://github.com/decred/dcrdex/pull/1543 @buck54321 
Let's close this since it's a dup

**Closed by chappjc** 2023-03-27 12:57 UTC
