### ISSUE TITLE
client: error when restoring from seed

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1172] opened 2021-08-26 23:35 UTC
When restoring from seed, seeing error message: **Connection to dex server failed. You can close dexc and try again later or wait for it to reconnect.**

**Comment by itswisdomagain** [comment] 2021-08-28 08:45
Anyone on this? I'll like to take it up. Perhaps with some of the review comments on https://github.com/decred/dcrdex/pull/1015#pullrequestreview-720777620. Separate commits for each to allow easier review. That's if no one is already on this.

**Comment by buck54321** [comment] 2021-08-28 13:33
You got it, @itswisdomagain.

**Comment by chappjc** [comment] 2021-08-31 21:15
@itswisdomagain Can you describe the root cause of the error?

**Comment by chappjc** [comment] 2021-08-31 21:31
Hmm, an earlier version of @buck54321's #1015 PR had a process to promote a temp conn to a full fledged one by starting the listener.
Seems like we need to have it set both `ConnectEventFunc` and `ReconnectSync`, not just `ConnectEventFunc`.  When you removed the call back setters, @buck54321, how did that work out?

**Comment by chappjc** [comment] 2021-08-31 21:36
Ah, it was this `reportingConnects` flag?  So the intent was always to have the connect handler configured, just with this flag to start/stop reporting?

What I'm still wondering about is don't we also need the Reconnect handler configured too and modulated by the same atomic flag?

**Comment by itswisdomagain** [comment] 2021-09-01 00:44
Yeah, that's the issue. They were both set when I last checked the PR, but when debugging the issue on master, noticed they were now only set conditionally.

The fix is in https://github.com/decred/dcrdex/pull/1183/commits/d2ae380eedbd194e107fc7fc81e34daf74549154, although you just reminded me something I missed - setting the reconnect handler when the connection is promoted to permanent. Do you mean to say that is already taken care of just by putting the connection in the `c.conns` map?

**Comment by itswisdomagain** [comment] 2021-09-01 01:15
I think I see what you mean re the conns map and the reconnect handler, if the reconnect handler was set even for temp dcs, it wouldn't actually do anything until and unless a reconnect happens _after_ the dc is added to the conns map:

https://github.com/decred/dcrdex/blob/015961e1293079f3c356b48d6378499a0f4cf83e/client/core/core.go#L4947-L4965

So it looks safe to always set `wsCfg.ReconnectSync` in `core.connectDEX` even for temp dcs.

Although I think it'd be smarter to allow `dc.refreshServerConfig()` before exiting that reconnect handler so if a reconnect happens before the dc is made permanent, any associated server config changes won't be lost.

**Closed** 2021-09-09 03:50 UTC
