### ISSUE TITLE
register: timed out waiting for 'notifyfee' response

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#392] opened 2020-05-20 09:38 UTC
Sometimes, after registereing, and the required number of blocks have been mined, the client throws this error:
`[ERR] CORE: notify: |ERROR| (fee payment) Fee payment error - Error encountered while paying fees to https://127.0.0.1:7232: timed out waiting for 'notifyfee' response.`

If this happens, the account does not seem to be salvageable. The db must be erased.

@buck54321 has also noticed this
>I've mentioned it before somewhere. I see it quite a bit. It seems to happen if I mine two reg confirmation blocks in very quick succession. I believe to be a server bug, but haven't gotten into it yet.

**Comment by JoeGruffins** [comment] 2020-05-26 12:08
Looking into this.

**Comment by JoeGruffins** [comment] 2020-05-26 13:22
It looks like the txout is being spent before notifyfee searches for it in some cases. Not sure if it's the server or the client yet. Could be cause by using the same wallet for both.

**Comment by chappjc** [comment] 2020-05-26 22:48
@buck54321 and I chatted about spend vs unspent requirements in a slightly different context, the swap contract, but I think client/asset implementations are probably also requiring these to be unspent rather than just any output.

**Comment by chappjc** [comment] 2020-05-26 23:26
If it's being spent, I suspect it's the simnet harness wallet doubling as both the client wallet and the server's fee wallet.  When DCR mines a block, the wallet client has a chance of using the fee payment to buy tickets, thus.

This makes `auth.FeeChecker` (`(dcr.Backend).UnspentCoinDetails`) unable to find the fee output.  I have the makings of a fix for this in https://github.com/decred/dcrdex/pull/406

**Comment by JoeGruffins** [comment] 2020-05-27 00:25
The harness is buying tickets? That explains it then, and makes sense.

While I think this particular issue could also be solved by supplying the server with an xpub from a different account, it shows that an operator who simply moves their funds gathered from fees could disrupt registration, which should not be the case, and can be solved by using `getrawtransaction` rather than `gettxout`.

**Comment by isuldor** [comment] 2020-06-04 22:57
I tried registering on the testnet dex a couple times and saw this error too.

> 2020-06-04 15:49:44.061 [DBG] CORE: Registration fee txn db44c708fcbcf3593370f197d1ea2d6db74b321eebd34d2276ae3855773821d0:0 now has 1 confirmations.
> 2020-06-04 15:49:44.061 [INF] CORE: Notifying dex dex-test.ssgen.io:7232 of fee payment.
> 2020-06-04 15:49:54.066 [ERR] CORE: notify: |ERROR| (feepayment) Fee payment error - Error encountered while paying fees to dex-test.ssgen.io:7232: timed out waiting for 'notifyfee' response.

**Comment by chappjc** [comment] 2020-06-05 03:13
Well, this is certainly a debilitating regression.  I see it on the testnet server too, but not a local simnet server.  The error was reproducible with the server running at f16e0427306bcedcf3e575b042c53b7e656c3ec4, and at current master (048ee403851c283d9756b0f4ecae1b9836b112c6).

It seems to be an issue with the server's auth module, as dcrdex is saying:

```
[ERR] AUTH: Send requested for unknown user f7cd2894a7792d6b9c89d2de0cece5432afcf8f6e067b0c4a98f81b960ebdfd9
```

**Comment by chappjc** [comment] 2020-06-05 03:17
Oh thank got, it's just the server's dcrd testnet node being stuck!  Phew!  dcrd seems to be stuck at 437025 (actual tip is more like 439933 right now).

But there's an opportunity to improve things her.  We should look at how stuck chains can be handled, and how coin waiters failing can possibly communicate the issue rather than simply not responding to the notify_fee request from the client.

**Comment by chappjc** [comment] 2020-06-05 03:34
It looks like this was seen with local nodes though, perhaps with fast blocks or reorgs?  So there may be something still to investigate on this issue, but dex-test.ssgen.io:7232 is working again after dcrd got moving.

**Closed** 2020-06-15 21:14 UTC
