### ISSUE TITLE
stalled dcrdex shutdown

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrdex#431] opened 2020-05-31 20:29 UTC
If dcrd is shut down before dcrdex, dcrdex shutdown stalls at `Auth manager shutdown.`

**Comment by JoeGruffins** [comment] 2020-06-01 02:15
Stalls forever, or just takes a while? I thought this was solved by https://github.com/decred/dcrdex/pull/325

**Comment by JoeGruffins** [comment] 2020-06-01 02:16
duplicate of https://github.com/decred/dcrdex/issues/321

**Closed** 2020-06-06 08:00 UTC
