### ISSUE TITLE
Updated password not persisted

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1036] opened 2021-04-05 17:05 UTC
from @alexlyp on Element:

> so something i noticed during a recent test run i was working on. I have my dcrwallet fully registered and working with dexc. i then update the private passphrase of the wallet. close everything down then restart. dexc appears to connect with wallet as expected after login, and then any attempt to buy/sell/unlock it correctly errors due to not the correct passphrase. then within the dexc/site i update the wallet private pass and i'm able to do everything from there. but when i restart everything, it's like dexc doesn't save that updated wallet passphrase and complains about incorrect pass
guessing it should be easily reproducible via CLI

**Comment by amassarwi** [comment] 2021-04-05 17:56
Will look into it.

**Comment by chappjc** [comment] 2021-04-05 19:24
Thanks for looking into it @amassarwi, but before that, pls hit up https://github.com/decred/dcrdex/pull/1016

**Comment by amassarwi** [comment] 2021-04-05 20:24
Sure thing on it now

**Comment by amassarwi** [comment] 2021-04-06 13:51
from @alexlyp on Element:
> ah turns out i was just doing something incorrect in my code

I guess we can close this one ?

**Comment by chappjc** [comment] 2021-04-06 17:08
Hmm, possibly.  I thought that comment was with regard to something else.  Can we first verify that the wallet password can be changed, dexc shutdown, and it uses the new password?

**Comment by alexlyp** [comment] 2021-04-06 18:24
That was in reference to the "empty vs nil passphrase" discussion we were having yesterday.  This issue should definitely be reproducible.

**Comment by amassarwi** [comment] 2021-04-06 18:26
oh i see, looking into it

**Comment by alexlyp** [comment] 2021-04-06 18:31
It should be easily reproducible by doing the following.  Start dexc, login and connect to existing dcrwallet.  Change the dcrwallet private passphrase then attempt to place an order.  It should error due to incorrect passphrase.  Then go to the wallets page and click the gears to update the passphrase.  Then you should be able to unlock the wallet.  Then shut everything down then restart dexc, login and attempt to place an order.  Should error for bad pass. 

That is the steps I have taken, only difference being it's logging in via decrediton (but it's still using the same internal passphrase update in the site/ )

**Closed** 2021-04-13 14:53 UTC
