### ISSUE TITLE
UI: Fail creating wallet but symbol shows unlocked and syncing.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrdex#1763] opened 2022-08-05 10:52 UTC
Here I have failed to create a zcash wallet for reasons, but the symbol on the left says it is unlocked and syncing. Probably the symbol should still be `x` and `no wallet`. Reloading the page fixes it.
![image](https://user-images.githubusercontent.com/34998433/183062509-71dd7b13-6e50-4960-97b3-bd5afb646408.png)

**Comment by chappjc** [comment] 2022-08-05 15:51
Probably would be fixed by https://github.com/decred/dcrdex/pull/1757 if that's an acceptable diff.

**Comment by JoeGruffins** [comment] 2022-08-09 06:22
Actually still seeing this with #1757 in.

**Comment by JoeGruffins** [comment] 2022-08-18 06:06
This also leads to a ghost wallet on the new wallet page:
![image](https://user-images.githubusercontent.com/34998433/185306023-66e81957-e097-4431-997f-84e2f5f9a965.png)
![image](https://user-images.githubusercontent.com/34998433/185306099-cef894ab-b3bd-4564-9968-c75993025e25.png)

**Comment by ukane-philemon** [comment] 2022-09-17 17:03
@JoeGruff: how long did you have to wait for zcash to sync to tip? 

BTW, does this issue affect Doge too? I see in the first image you where trying to create a zcash wallet and the last image has a doge ghost wallet.

**Comment by JoeGruffins** [comment] 2022-09-19 05:27
@ukane-philemon zcash took... a bit? I have slow internet but was more than a day I think.

> BTW, does this issue affect Doge too?

Yes.

**Comment by ukane-philemon** [comment] 2022-09-19 07:10
> zcash took... a bit?

Zcash syncing starts from the beginning if the zcashd deamon exits. It's a bit fustrating to get zcash testnet ready.

**Comment by ukane-philemon** [comment] 2022-10-18 22:43
> Here I have failed to create a zcash wallet for reasons, but the symbol on the left says it is unlocked and syncing. Probably the symbol should still be x and no wallet. Reloading the page fixes it.

@JoeGruffins, do you still see this? If possible, you can drop steps to reproduce the issue.

**Comment by JoeGruffins** [comment] 2022-10-24 08:45
Hmm, I cannot create a zcash wallet at all right now it seems.

**Comment by JoeGruffins** [comment] 2022-10-24 11:32
The NaN screen can be reproduced with the simnet harnest and doge. Start the harness with doge. Enter credentials for one of the wallets, like user: user, password: pass, address: 127.0.0.1, port: 23771 (gamma wallet)

Then enter a password for wallet and your app password. You should see the error "-15: Error: running with an unencrypted wallet, but walletpassphrase was called." And going back you see the NaN screen with ghost wallet.

**Comment by ukane-philemon** [comment] 2022-10-24 13:45
Running zec harness. Don't really have a clue why it's failing with `CDB: Error 2, can't open database`

<details>
<summary> Zec Harness Log </summary>

```
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmT6xPT7WzDFWkag9B6mnJ289BN1xCRBkWT 7; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmSog4freWuq1aC13yf1996fy4qXPmv3GTB 1; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmErjeuUGzZdwvRzGh4ASmHCXVyZMGqzqmJ 1; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmT6xPT7WzDFWkag9B6mnJ289BN1xCRBkWT 1; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmSog4freWuq1aC13yf1996fy4qXPmv3GTB 15; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmErjeuUGzZdwvRzGh4ASmHCXVyZMGqzqmJ 15; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmT6xPT7WzDFWkag9B6mnJ289BN1xCRBkWT 15; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmSog4freWuq1aC13yf1996fy4qXPmv3GTB 3; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmErjeuUGzZdwvRzGh4ASmHCXVyZMGqzqmJ 3; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmT6xPT7WzDFWkag9B6mnJ289BN1xCRBkWT 3; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmSog4freWuq1aC13yf1996fy4qXPmv3GTB 25; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmErjeuUGzZdwvRzGh4ASmHCXVyZMGqzqmJ 25; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./alpha sendtoaddress tmT6xPT7WzDFWkag9B6mnJ289BN1xCRBkWT 25; tmux wait-for -S zec
error code: -6
error message:
Insufficient funds
bash-3.2$ ./mine-alpha 2; tmux wait-for -S zec
error code: -1
error message:
CDB: Error 2, can't open database 
```
</details>

**Comment by chappjc** [comment] 2022-10-24 13:46
Check the zcashd tmux pane @ukane-philemon

**Comment by ukane-philemon** [comment] 2022-10-24 13:49
The log is from the zcash tmux window.

**Comment by chappjc** [comment] 2022-10-24 13:51
No that's from the ctl pane.  You need to switch panes with CTRL+B followed by 0 or 1 or 2 or 3 to get to the node panes

**Comment by ukane-philemon** [comment] 2022-10-24 13:53
> No that's from the ctl pane. You need to switch panes with CTRL+B followed by 0 or 1 or 2 or 3 to get to the node panes.
> 
> You're seeing insufficient funds and a database failure, so something is wrong with zcashd there.

I'm on this pane `[zec-harne0:alpha  1:beta  2:delta  3:gamma- 4:harness-ctl*`.

**Comment by chappjc** [comment] 2022-10-24 13:56
That's the list of *panes* for that tmux *window*.  There are 5.  The one with the "*" is the pane you are on (`harness-ctl`).  You need to switch from the ctl pane to the node panes.

![image](https://user-images.githubusercontent.com/9373513/197543218-7ca46b43-6e4e-4a25-8ab5-a5adb724fc3c.png)

**Comment by ukane-philemon** [comment] 2022-10-24 14:01
<details>

```
2022-10-24T13:58:16.769148Z  INFO main: Zcash version v5.2.0 (2022-07-26 09:03:35 -0600)
2022-10-24T13:58:16.769211Z  INFO Init: main: InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2022-10-24T13:58:16.769574Z DEBUG Init: mempool: Setting mempool cost limit: (limit=80000000, time=3600)
2022-10-24T13:58:16.769755Z  INFO Init: main: Setting network upgrade activation parameters for 5ba81b19 to height=1
2022-10-24T13:58:16.769780Z  INFO Init: main: Setting network upgrade activation parameters for 76b809bb to height=1
2022-10-24T13:58:16.769800Z  INFO Init: main: Setting network upgrade activation parameters for 2bb40e60 to height=1
2022-10-24T13:58:16.769819Z  INFO Init: main: Setting network upgrade activation parameters for f5b9230b to height=1
2022-10-24T13:58:16.769838Z  INFO Init: main: Setting network upgrade activation parameters for e9ff75a6 to height=2
2022-10-24T13:58:16.769859Z  INFO Init: main: Setting network upgrade activation parameters for c2d6d0b4 to height=3
2022-10-24T13:58:16.769989Z  INFO Init: main: Using the 'sse4(1way),sse41(4way)' SHA256 implementation
2022-10-24T13:58:16.780674Z  INFO Init: main: Using BerkeleyDB version Berkeley DB 6.2.23: (March 28, 2016)
2022-10-24T13:58:16.780735Z  INFO Init: main: Default data directory /Users/philemon/Library/Application Support/Zcash
2022-10-24T13:58:16.780751Z  INFO Init: main: Using data directory /Users/philemon/dextest/zec/delta/regtest
2022-10-24T13:58:16.780796Z  INFO Init: main: Using config file /Users/philemon/dextest/zec/delta/delta.conf
2022-10-24T13:58:16.780815Z  INFO Init: main: Using at most 125 connections (275 file descriptors available)
2022-10-24T13:58:16.790305Z  INFO Init: main: Using 16 MiB out of 16 requested for signature cache, able to store 524288 elements
2022-10-24T13:58:16.795134Z  INFO Init: main: Using 8 MiB out of 8 requested for Sapling bundle cache, able to store 262144 elements
2022-10-24T13:58:16.799712Z  INFO Init: main: Using 8 MiB out of 8 requested for Orchard bundle cache, able to store 262144 elements
2022-10-24T13:58:16.799813Z  INFO Init: main: Using 4 threads for script verification
2022-10-24T13:58:16.800063Z  INFO main: scheduler thread start
2022-10-24T13:58:16.800176Z  INFO Init: main: Loading Sapling (Spend) parameters from /Users/philemon/Library/Application Support/ZcashParams/sapling-spend.params
2022-10-24T13:58:16.800193Z  INFO Init: main: Loading Sapling (Output) parameters from /Users/philemon/Library/Application Support/ZcashParams/sapling-output.params
2022-10-24T13:58:16.800202Z  INFO Init: main: Loading Sapling (Sprout Groth16) parameters from /Users/philemon/Library/Application Support/ZcashParams/sprout-groth16.params
2022-10-24T13:58:19.142979Z  INFO Init: main: Loading Orchard parameters
2022-10-24T13:58:31.818697Z  INFO Init: main: Loaded proof system parameters in 15.018412s seconds.
2022-10-24T13:58:31.821309Z  INFO Init: main: Binding RPC on address ::1 port 33770 failed.
2022-10-24T13:58:31.821372Z  INFO Init: main: Binding RPC on address 127.0.0.1 port 33770 failed.
2022-10-24T13:58:31.821389Z  INFO Init: main: Unable to bind any endpoint for RPC server
2022-10-24T13:58:31.821426Z  INFO Init: main: Error: Unable to start HTTP server. See debug log for details.
Error: Unable to start HTTP server. See debug log for details.
2022-10-24T13:58:31.821467Z DEBUG rpc: Interrupting HTTP RPC server
2022-10-24T13:58:31.821475Z DEBUG rpc: Interrupting RPC
2022-10-24T13:58:31.821538Z DEBUG Shutdown: rpc: Stopping HTTP RPC server
2022-10-24T13:58:31.821566Z DEBUG Shutdown: rpc: Stopping RPC
2022-10-24T13:58:31.821625Z DEBUG Shutdown: rpc: RPC stopped.
2022-10-24T13:58:31.821629Z  INFO main: scheduler thread interrupt
2022-10-24T13:58:31.821649Z  INFO Shutdown: main: StopRPC: waiting for async rpc workers to stop
2022-10-24T13:58:31.821715Z  INFO Shutdown: main: StopNode()
2022-10-24T13:58:31.822009Z  INFO Shutdown: main: done
```

</details>

**Comment by ukane-philemon** [comment] 2022-10-24 14:02
> That's the list of windows for that tmux session There are 5.

I switched with `tmux attach -t zec-harness:1`

**Comment by chappjc** [comment] 2022-10-24 14:03
It can't bind to 33770 so it isn't running.  I think you already have a process bound to that port.  Probably you have another zcashd running somewhere (check `ps` and `tmux ls`), otherwise some other unrelated process just happens to want the port (see `netstat -lnp`)

> I switched with tmux attach -t zec-harness:1

Just use CTRL+B, <number>

**Comment by ukane-philemon** [comment] 2022-10-24 14:09
> some other unrelated process just happens to want the port

yeah, killed all tmux zec-harness but I still got this ->

```
netstat -vanp tcp | grep 33770                        
tcp4       0      0  127.0.0.1.33770        *.*                    LISTEN      131072 131072   1689      0 0x0100 0x0000000e
tcp6       0      0  ::1.33770              *.*                    LISTEN      131072 131072   1689      0 0x0100 0x0000000e

```

**Comment by chappjc** [comment] 2022-10-24 14:11
Do you kill with `./quite` from the `harness-ctl` windows?

Also, you may need to run `netstat` with sudo or as root because it's not showing what process is bound.

**Comment by ukane-philemon** [comment] 2022-10-24 14:14
I had killed the process `1689` but still get the db error.

```
+ tmux send-keys -t zec-harness:4 './alpha generate 400; tmux wait-for -S zec' 'C-m;' wait-for zec
+ ALPHA_ADDR=tmEgW8c44RQQfft9FHXnqGp8XEcQQSRcUXD
+ BETA_ADDR=tmSog4freWuq1aC13yf1996fy4qXPmv3GTB
++ ./delta getnewaddress
+ DELTA_ADDR=tmVLo5WDjMywgr7v4vUw1G5ZhSsgYdkwbdc
++ ./gamma getnewaddress
error code: -1
error message:
CDB: Error 2, can't open database  // db error
+ GAMMA_ADDR=
philemon@Philemons-MBP zec % sudo lsof -i tcp:33770 // even after kill these process it still won't run.
COMMAND  PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
zcashd  5029 philemon    8u  IPv6 0x2142747d64ced8e5      0t0  TCP localhost:33770 (LISTEN)
zcashd  5029 philemon    9u  IPv4 0x2142747d56e067f5      0t0  TCP localhost:33770 (LISTEN)
philemon@Philemons-MBP zec % 

```

**Comment by ukane-philemon** [comment] 2022-10-24 16:32
> 23771

I get the error but no ghost wallet.
<img width="516" alt="Screenshot 2022-10-24 at 5 31 45 PM" src="https://user-images.githubusercontent.com/57448127/197578074-a4669f15-9b45-4cb8-8ddb-46cac9867187.png">

**Comment by ukane-philemon** [comment] 2022-10-24 16:34
Also, not providing a wallet password seems to fix the issue because the wallet is `unencrypted`.

**Comment by chappjc** [comment] 2022-10-24 16:37
> Also, not providing a wallet password seems to fix `-15: Error: running with an unencrypted wallet, but walletpassphrase was called.` error because the wallet is `unencrypted`?

Yes, that was not the issue though.  That was just an easy repro for the NaN wallet.  The error is expected.
FWIW, I haven't tried to repro it though.

**Comment by ukane-philemon** [comment] 2022-10-24 16:38
> That was just an easy repro for the NaN wallet

Yeah, the repro didn't work from my end.

**Comment by JoeGruffins** [comment] 2022-10-25 01:46
Really? Huh... I'll make a video of what I see. Using Firefox if that matters.

**Comment by JoeGruffins** [comment] 2022-10-25 02:18
![dogefake](https://user-images.githubusercontent.com/34998433/197666479-3fd0c1f6-4af2-4079-b722-68f4977944d7.gif)

**Comment by ukane-philemon** [comment] 2022-10-25 05:03
> Really? Huh... I'll make a video of what I see. Using Firefox if that matters.

Oh, you're using Firefox. I tried to repro on chrome. Do you by any chance see it on chrome too?

**Comment by JoeGruffins** [comment] 2022-10-25 05:04
I'll download Chrome and try...

**Comment by chappjc** [comment] 2022-10-25 17:04
I can reproduce this too

![image](https://user-images.githubusercontent.com/9373513/197837359-5280391c-cdda-44d4-a14b-60f829ce0cc6.png)

after page refresh, it goes back to "Create a wallet" instead of NaN

**Comment by ukane-philemon** [comment] 2022-10-25 17:08
> > Really? Huh... I'll make a video of what I see. Using Firefox if that matters.
> 
> Oh, you're using Firefox. I tried to repro on chrome. Do you by any chance see it on chrome too?

Strange am unable to reproduce the ghost wallet on firefox too. Maybe try `npm i` then build js files again. I'm using the `--no-embed-site` flag.

https://user-images.githubusercontent.com/57448127/197811604-c8cbdbb0-d5d2-4135-8039-37ddc0cf944f.mov

**Comment by chappjc** [comment] 2022-10-25 17:39
If I do `enableLogger('notes', true)` and then make the request, I see this in the console:

![image](https://user-images.githubusercontent.com/9373513/197841607-b3e76486-0264-4b9f-a358-e5fd02e21a8e.png)

A `walletstate` note comes through even though wallet construction isn't successful.  And the NaN symptom clearly comes from an incomplete `balance` object.

If this was not happening on release 0.5 (is it?) we should identify the change that is the root cause.

**Comment by ukane-philemon** [comment] 2022-10-25 17:40
> BTW, you should generally not do npm i since that ignores the package-lock.json. Instead use npm ci.

yeah, I use `ci`.

**Comment by chappjc** [comment] 2022-10-25 18:12
I think a `if atomic.LoadUint32(w.broadcasting) == 1 {` needs to be around one of the `c.notify(newWalletStateNote(wallet.state()))` calls, probably in one of the connect helpers.  Will look into it more.

**Closed** 2022-11-03 17:05 UTC
Labels: bug, client, UI
